package ability

import (
	"errors"
	"io"
	"os"
	"strings"

	"github.com/grandper/go-screenplay/screenplay"
)

var (
	// ErrFileAlreadyExists is returned when the file already exists.
	ErrFileAlreadyExists = errors.New("file already exists")
)

// UseTheFileSystem represents the ability of an actor to use the file system.
func UseTheFileSystem() *UseTheFileSystemAbility {
	return &UseTheFileSystemAbility{}
}

// UseTheFileSystemAbility represents the ability of an actor to use the file system.
type UseTheFileSystemAbility struct{}

// CurrentPath returns the path.
func (a *UseTheFileSystemAbility) CurrentPath() (string, error) {
	return os.Getwd()
}

// ChangeDirectory changes the current directory.
func (a *UseTheFileSystemAbility) ChangeDirectory(dir string) error {
	return os.Chdir(dir)
}

// FileExists returns true if the file exists.
func (a *UseTheFileSystemAbility) FileExists(filename string) (bool, error) {
	info, err := os.Stat(filename)
	if err == nil {
		return !info.IsDir(), nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, err
}

// DirectoryExists returns true if the directory exists.
func (a *UseTheFileSystemAbility) DirectoryExists(director string) (bool, error) {
	info, err := os.Stat(director)
	if err == nil {
		return info.IsDir(), nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, err
}

// CreateTemporaryFile creates a new temporary file in the directory dir,
// opens the file for reading and writing, and returns the resulting file.
// The filename is generated by taking pattern and adding a random
// string to the end. If pattern includes a "*", the random string replaces
// the last "*". If dir is the empty string, CreateTemp uses the default
// directory for temporary files, as returned by TempDir. Multiple programs
// or goroutines calling CreateTemp simultaneously will not choose the same
// file. The caller can use the file's Name method to find the pathname of
// the file. It is the caller's responsibility to remove the file when it
// is no longer needed.
func (a *UseTheFileSystemAbility) CreateTemporaryFile(pattern string) (string, error) {
	file, err := a.createTemporaryFile(pattern)
	if err != nil {
		return "", err
	}
	return file.Name(), file.Close()
}

// CreateTemporaryFileWithContent creates a new file with the specified name and copies the content from the provided reader.
func (a *UseTheFileSystemAbility) CreateTemporaryFileWithContent(pattern string, reader io.Reader) (string, error) {
	file, err := a.createTemporaryFile(pattern)
	if err != nil {
		return "", err
	}
	defer file.Close()
	_, err = io.Copy(file, reader)
	if err != nil {
		return "", err
	}
	return file.Name(), nil
}

func (a *UseTheFileSystemAbility) createTemporaryFile(pattern string) (*os.File, error) {
	if strings.Contains(pattern, "*") {
		return os.CreateTemp("", pattern)
	}
	exists, err := a.FileExists(pattern)
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, ErrFileAlreadyExists
	}
	return os.CreateTemp("", pattern)
}

// CreateFile creates a new file with the specified name.
func (a *UseTheFileSystemAbility) CreateFile(filename string) error {
	file, err := a.createFile(filename)
	if err != nil {
		return err
	}
	return file.Close()
}

// CreateFileWithContent creates a new file with the specified name and copies the content from the provided reader.
func (a *UseTheFileSystemAbility) CreateFileWithContent(filename string, reader io.Reader) error {
	file, err := a.createFile(filename)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = io.Copy(file, reader)
	if err != nil {
		return err
	}
	return nil
}

func (a *UseTheFileSystemAbility) createFile(filename string) (*os.File, error) {
	exists, err := a.FileExists(filename)
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, ErrFileAlreadyExists
	}
	file, err := os.Create(filename)
	if err != nil {
		return nil, err
	}
	return file, nil
}

// OverwriteFileWithContent overwrites the content of the specified file with the content from the provided reader.
func (a *UseTheFileSystemAbility) OverwriteFileWithContent(filename string, reader io.Reader) error {
	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = io.Copy(file, reader)
	if err != nil {
		return err
	}
	return nil
}

// AppendTo appends content from the provided reader to the specified file.
func (a *UseTheFileSystemAbility) AppendTo(filename string, reader io.Reader) error {
	file, err := os.OpenFile(filename, os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer file.Close()
	_, err = io.Copy(file, reader)
	if err != nil {
		return err
	}
	return nil
}

// Read reads the content of the specified file and returns it as a byte slice.
func (a *UseTheFileSystemAbility) Read(filename string) ([]byte, error) {
	return os.ReadFile(filename)
}

// CreateDirectory creates a new directory with the specified name and permission bits.
func (a *UseTheFileSystemAbility) CreateDirectory(name string, perm os.FileMode) error {
	return os.Mkdir(name, perm)
}

// CreateTemporaryDirectory creates a new temporary directory with the specified name and permission bits.
func (a *UseTheFileSystemAbility) CreateTemporaryDirectory(pattern string) (string, error) {
	return os.MkdirTemp("", pattern)
}

// RemoveTheFile removes the named file or (empty) directory.
func (a *UseTheFileSystemAbility) RemoveTheFile(filename string) error {
	return os.Remove(filename)
}

// RemoveDirectory removes a directory and its content.
func (a *UseTheFileSystemAbility) RemoveDirectory(name string) error {
	return os.RemoveAll(name)
}

// Forget clean up the ability.
// The ability cannot be used after Forget() has been called.
// This method is used, e.g., to close connections to databases,
// deleting data, closing client cleanly.
func (a *UseTheFileSystemAbility) Forget() error {
	return nil
}

// Ensure UseTheFileSystemAbility implements the Ability interface.
var _ screenplay.Ability = (*UseTheFileSystemAbility)(nil)
